********************************************************************************
* Title:   Multiple Hypothesis Tests
* Descrip: Multiple hypothesis tests are run using the rwolf2 command for the 
*          Romano-Wolf correction and the wyoung command for the Holm-Conferroni 
*          correction. The tables are reported in the Appendix
*          Table A1: MHT Compensation-Experiment
*          Table A4: MHT Additional Treatments
*          Table A6: MHT Earnings-experiment 
*          Table A8: MHT Comparison of experiments
*          Table A10: MHT Unemployment-experiment  
*          NB: The multiple hypothesis tables do not produce an exportable output -
*          the tables were generated manually because the commands rwolf2 and wyoung
*          do not allow for exportable output in the form of matrices or tabes. 
*          The replicator can expect discrepansies between the generated output and 
*          the output reported in the manuscript because...
********************************************************************************

clear all
set more off
cap log close
log using ../Code/mht_Type1Type2_2022.log, text replace

use ../Data/Processed_Data/analyticaldata.dta, clear 
********************************************************************************
**#A1. MHT COMP.EXP.
********************************************************************************
*ROMANO-WOLF CORRECTION
*Romano-Wolf p-value is the value of interest
*all 
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment<6 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)  
*usa
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==0 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==0 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)
*nor
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==1 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==1 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)


*HOLM-BONFERRONI CORRECTION
*pbonf is the value of interest
*all
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 [pweight=sca_weight], robust") familyp("prob25" "prob50" "prob75" "prob100""prob25" "prob50" "prob75" "prob100") boot(10000)
*usa
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==0 [pweight=sca_weight], robust") familyp("prob25" "prob50" "prob75" "prob100""prob25" "prob50" "prob75" "prob100") boot(10000)
*nor
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment<6 & Norway==1 [pweight=sca_weight], robust") familyp("prob25" "prob50" "prob75" "prob100""prob25" "prob50" "prob75" "prob100") boot(10000) 

********************************************************************************
**#A4. MHT ADDITIONLA TREATMENTS
********************************************************************************
*ROMANO-WOLF CORRECTION
*all
rwolf2 (reg pay national male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==6) (reg pay high male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==7) (reg pay comp male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==8) (reg pay lowcost highcost male lowage lowincome loweducation rightwing if h_treatment>7 & h_treatment<11), indepvars(national, high, comp, lowcost highcost) reps(250) 
*usa
rwolf2 (reg pay national male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==6) (reg pay high male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==7) (reg pay comp male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==8) (reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==0 & h_treatment>7 & h_treatment<11), indepvars(national, high, comp, lowcost highcost) reps(250) 
*nor
rwolf2 (reg pay national male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==6) (reg pay high male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==7) (reg pay comp male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==8) (reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==1 & h_treatment>7 & h_treatment<11), indepvars(national, high, comp, lowcost highcost) reps(250) 

*HOLM-BONFERRONI CORRECTION
*all
wyoung, cmd("reg pay national male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==6" "reg pay high male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==7" "reg pay comp male lowage lowincome loweducation rightwing if h_treatment==3 | h_treatment==8" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if h_treatment>7 & h_treatment<11" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if h_treatment>7 & h_treatment<11") familyp("national" "high" "comp" "lowcost" "highcost") boot(10000)
*usa
wyoung, cmd("reg pay national male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==6" "reg pay high male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==7" "reg pay comp male lowage lowincome loweducation rightwing if Norway==0 & h_treatment==3 | Norway==0 & h_treatment==8" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==0 & h_treatment>7 & h_treatment<11" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==0 & h_treatment>7 & h_treatment<11") familyp("national" "high" "comp" "lowcost" "highcost") boot(10000)
*nor
wyoung, cmd("reg pay national male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==6" "reg pay high male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==7" "reg pay comp male lowage lowincome loweducation rightwing if Norway==1 & h_treatment==3 | Norway==1 & h_treatment==8" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==1 & h_treatment>7 & h_treatment<11" "reg pay lowcost highcost male lowage lowincome loweducation rightwing if Norway==1 & h_treatment>7 & h_treatment<11") familyp("national" "high" "comp" "lowcost" "highcost") boot(10000)

********************************************************************************
**#A6. MHT EARN.EXP.
********************************************************************************
*ROMANO-WOLF CORRECTION
*all 
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)
*usa
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)
*nor
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)

*HOLM-BONFERRONI CORRECTION
*all
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)
*usa
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==0 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)
*nor
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>15 & h_treatment<21 & Norway==1 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)

********************************************************************************
**#A8A. MHT COMPARISON COMP. VS. EARN.
********************************************************************************
*ROMANO-WOLF CORRECTION
*all
rwolf2 (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust), indepvars(replication replication_prob25 replication_prob50 replication_prob75 replication_prob100, replication replication_prob25 replication_prob50 replication_prob75 replication_prob100) reps(250)
*usa
rwolf2 (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust), indepvars(replication replication_prob25 replication_prob50 replication_prob75 replication_prob100, replication replication_prob25 replication_prob50 replication_prob75 replication_prob100) reps(250)
*nor
rwolf2 (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust), indepvars(replication replication_prob25 replication_prob50 replication_prob75 replication_prob100, replication replication_prob25 replication_prob50 replication_prob75 replication_prob100) reps(250)

*HOLM-BONFERRONI CORRECTION
*all
wyoung, cmd ("reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust") familyp("replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100" "replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100") boot(10000)
*usa
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust") familyp("replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100" "replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100") boot(10000)
*nor
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 replication replication_prob25 replication_prob50 replication_prob75 replication_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>15 & h_treatment<21) [pweight=sca_weight], robust") familyp("replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100" "replication" "replication_prob25" "replication_prob50" "replication_prob75" "replication_prob100") boot(10000)



********************************************************************************
**#A8B. MHT COMPARISON COMP. VS. UNEMP.
******************************************************************************** 
*ROMANO-WOLF CORRECTION
*All 
rwolf2 (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust) (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust), indepvars(unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100, unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100) reps(250)
*usa
rwolf2 (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust), indepvars(unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100, unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100) reps(250)
*nor
rwolf2 (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust), indepvars(unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100, unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100) reps(250)

*HOLM-BONFERRONI CORRECTION
*all
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 [pweight=sca_weight] if (h_treatment<6 | h_treatment>10 & h_treatment<16), robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust") familyp ("unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100" "unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100") boot(10000)
*usa
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==0 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust") familyp ("unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100" "unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100") boot(10000)
*nor
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 unemployment unemployment_prob25 unemployment_prob50 unemployment_prob75 unemployment_prob100 male lowage lowincome loweducation rightwing if Norway==1 & (h_treatment<6 | h_treatment>10 & h_treatment<16) [pweight=sca_weight], robust") familyp ("unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100" "unemployment" "unemployment_prob25" "unemployment_prob50" "unemployment_prob75" "unemployment_prob100") boot(10000)

********************************************************************************
**#A10. MHT UNEMP. EXP.
********************************************************************************
*ROMANO-WOLF CORRECTION
*all 
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)
*usa
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)
*nor
rwolf2 (reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust) (reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust), indepvars(prob25 prob50 prob75 prob100, prob25 prob50 prob75 prob100) reps(250)

*HOLM-BONFERRONI CORRECTION
*all
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)
*usa
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==0 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)
*nor
wyoung, cmd("reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust" "reg pay prob25 prob50 prob75 prob100 lowincome loweducation male lowage rightwing if h_treatment>10 & h_treatment<16 & Norway==1 [pweight=sca_weight], robust") familyp ("prob25" "prob50" "prob75" "prob100" "prob25" "prob50" "prob75" "prob100") boot(10000)

cap log close 